spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}
gemini.api.key=AIzaSyD2cY6F5rGIaX1VCiBuLNmMABcq0MdzHuo